// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSV_btLuVlQq4AH-guf4qXCOwL96lizHg',
    appId: '1:181000924561:web:345a523d86253cac1bfe30',
    messagingSenderId: '181000924561',
    projectId: 'guardpulse-e3d24',
    authDomain: 'guardpulse-e3d24.firebaseapp.com',
    storageBucket: 'guardpulse-e3d24.firebasestorage.app',
    measurementId: 'G-WT3BEY42LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtgEhuoCZQiWznXduQ675lhJT3RIqGBfo',
    appId: '1:181000924561:android:7e2b9b10a69d0e6d1bfe30',
    messagingSenderId: '181000924561',
    projectId: 'guardpulse-e3d24',
    storageBucket: 'guardpulse-e3d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbkYAsZuwbjWjnL9R0yX-aoKfoNsG1xR4',
    appId: '1:181000924561:ios:f35fd3cc4068f6f61bfe30',
    messagingSenderId: '181000924561',
    projectId: 'guardpulse-e3d24',
    storageBucket: 'guardpulse-e3d24.firebasestorage.app',
    iosBundleId: 'com.example.guardgrey.guardgrey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbkYAsZuwbjWjnL9R0yX-aoKfoNsG1xR4',
    appId: '1:181000924561:ios:f35fd3cc4068f6f61bfe30',
    messagingSenderId: '181000924561',
    projectId: 'guardpulse-e3d24',
    storageBucket: 'guardpulse-e3d24.firebasestorage.app',
    iosBundleId: 'com.example.guardgrey.guardgrey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSV_btLuVlQq4AH-guf4qXCOwL96lizHg',
    appId: '1:181000924561:web:9906bfcbab567fe01bfe30',
    messagingSenderId: '181000924561',
    projectId: 'guardpulse-e3d24',
    authDomain: 'guardpulse-e3d24.firebaseapp.com',
    storageBucket: 'guardpulse-e3d24.firebasestorage.app',
    measurementId: 'G-QMT0LMB0GL',
  );
}
